use_utm_origin: true
utm_origin_units: 1 # 0 - UTM, 1 - Latitude Longitude
utm_origin_lat: 41.22061603
utm_origin_lon: -8.52731407

world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 41.22061603
  origin_y: -8.52731407

safety_area:

  enabled: true

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "latlon_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: [
      41.22119, -8.52713,
      41.22096, -8.52706,
      41.22064, -8.52709,
      41.22058, -8.52755,
      41.22065, -8.52767,
      41.22076, -8.52766,
      41.22075, -8.52749,
      41.22103, -8.52739,
      41.22121, -8.52734
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 15.0
    min_z: 1.0