# global goal setting
global_goal:
  # swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  swarm_scale : 1.0
  relative_pos_0 : {x: 0.0, y: 0.0, z: 0.0}
  relative_pos_1 : {x: 2.5, y: -2.5, z: 0.0}
  relative_pos_2 : {x: -2.5, y: -2.5, z: 0.0}

uav_height: 3.0
distance_target: 0.5

wait_takeoff: false