## In the WITmotion windows app set:
# Band Width: 256Hz
# Baud rate; 230400
# Output rate: 200Hz
# Content: Accelaration | Velocity | Angle
# IMPORTANT NOTE: use always a original wit usb uart tll, otherwise you wont reach the 200Hz

witmotion_imu:
    port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 # serial/by-id/usb-FTDI_FT232R_USB_UART_AG0JZSXE-if00-port0
    baud_rate: 230400 #115200 # baud
    polling_interval: 5 # ms
    timeout_ms: 150 # ms
    restart_service_name: /restart_imu
    imu_publisher:
        #enabled: false #false #true
        topic_name: imu
        frame_id: imu_link
        use_native_orientation: false
        measurements:
            acceleration:
                enabled: true
                covariance: [ 0.0364,    0,       0,
                              0,         0.0048,  0,
                              0,         0,       0.0796 ]
            angular_velocity:
                enabled: true
                covariance: [ 0.0663,    0,       0,
                              0,         0.1453,  0,
                              0,         0,       0.0378 ]
            orientation:
                enabled: true
                covariance: [ 0.0479,    0,       0,
                              0,         0.0207,  0,
                              0,         0,       0.0041 ]
    temperature_publisher:
        enabled: false #true
        topic_name: temperature
        frame_id: base_link
        from_message: magnetometer # acceleration, angular_vel, orientation, magnetometer
        variance: 0.01829
        coefficient: 1.0 # Linear calibration parameters: coefficient
        addition: 0.0 # and addendum
    magnetometer_publisher:
        enabled: false #true
        topic_name: magnetometer
        frame_id: imu
        coefficient: 0.00000001 # Linear calibration parameters: coefficient
        addition: 0.0 # and addendum
        covariance: [ 0.000000187123,   0,              0,
                      0,                0.000000105373, 0,
                      0,                0,              0.000000165816  ]
    barometer_publisher:
        enabled: false #true
        topic_name: barometer
        frame_id: base_link
        variance: 0.001
        coefficient: 1.0 # Linear calibration parameters: coefficient
        addition: 0.0 # and addendum
    altimeter_publisher:
        enabled: false #true
        topic_name: altitude
        coefficient: 1.0 # Linear calibration parameters: coefficient
        addition: 0.0 # and addendum
    orientation_publisher:
        enabled: false #true
        topic_name: orientation
    gps_publisher:
        enabled: false
        navsat_fix_frame_id: world
        navsat_fix_topic_name: /gps
        navsat_altitude_topic_name: /gps_altitude
        navsat_satellites_topic_name: /gps_satellites
        navsat_variance_topic_name: /gps_variance
        ground_speed_topic_name: /gps_ground_speed
    rtc_publisher:
        enabled: true
        topic_name: witmotion_clock
        presync: true

