udp_topics:
  - name: "/uav6/distributedMapping/globalDescriptors"
  - name: "/uav6/distributedMapping/loopInfo"
  - name: "/uav6/distributedMapping/neighborPoseEstimates"
  - name: "/uav6/distributedMapping/neighborRotationEstimates"
  - name: "/uav6/distributedMapping/optimizationState"
  - name: "/uav6/distributedMapping/poseEstimateState"
  - name: "/uav6/distributedMapping/rotationEstimateState"
  - name: "/uav6/distributedMapping/path"
  - name: "/uav6/distributedMapping/globalMap"
  - name: "/uav6/octomap_planner/path"
  - name: "/uav6/move_base_simple/swarm"
topic_advertisement_rate: 10
topic_refresh_rate: 10
