udp_topics:
  - name: "/uav7/distributedMapping/globalDescriptors"
  - name: "/uav7/distributedMapping/loopInfo"
  - name: "/uav7/distributedMapping/neighborPoseEstimates"
  - name: "/uav7/distributedMapping/neighborRotationEstimates"
  - name: "/uav7/distributedMapping/optimizationState"
  - name: "/uav7/distributedMapping/poseEstimateState"
  - name: "/uav7/distributedMapping/rotationEstimateState"
  - name: "/uav7/distributedMapping/path"
  - name: "/uav7/distributedMapping/globalMap"
  - name: "/uav7/octomap_planner/path"
  - name: "/uav7/move_base_simple/swarm"
topic_advertisement_rate: 10
topic_refresh_rate: 10
