frame_id: "world_origin"

leader_msg: "mpc"
frame_publish: "utm_origin"

# octopmap planner frame
waypoint_frame: "world_origin"

timer_main:
  rate: 1.0 # [Hz]

timer_pose:
  rate: 1.0 # [Hz]

timer_comm:
  rate: 1.0 # [Hz]
  timeout: 20.0 # [s]

number_of_samples: 100
departure_time: 5.0 # [s], pair-based follower launch delay after first leader_index
enable_estimator_change: true
estimator_change_timer: 15.0 # [s], delay after flying_normally=true before calling change_estimator

center:
  x: 10.0 # [m]
  y: -4.0 # [m]
  z: 10.0 # [m]

dimensions:
  x: 150.0 # [m]
  y: 150.0 # [m]

angle: 2.35 #
lateral_scale: 1.0
side: 10.0

octomap_planner_set: true
leader_reference_set: false
heading_leader_zero: false